### ISSUE TITLE
Move to new repo (withings-sync)

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/withings-sync#1]
Continuation of [PR #21 from withings-garmin-v2](https://github.com/jaroslawhartman/withings-garmin-v2/pull/21#issue-469973696).

- [x]  Archive repository
- [x]  Add @jaroslawhartman as collaborator to PyPi project of withings-sync
- [x]  Activate GitHub Pages for new withings-sync repo in order to host CallBack URL from there (this allows us to use the withings.html from within the repo and therefor simplifying updates and removing dependencies on external services..
- [x] Move issues from old repo

**Comment by jaroslawhartman** [comment]
Hi Steffen,

As requested, callback URL updated to Github pages, it seems to be working. I've updated the URL in ec79e452376153f3ee92a904627fddae17b0b482

Regards,
Jarek

**Comment by stv0g** [comment]
Hi Jaroslaw,

thanks a lot 👍 I also moved the remaining open issues from the old repo.

Lets close this one here. Let me know once you have a pypi account.. I can add you later as well...

**Comment by jaroslawhartman** [comment]
I've created pypi account `jhartman`. Please add me when you will have time.

Thanks!

**Comment by stv0g** [comment]
Thanks. I added you as a project owner on pypi.org
