### ISSUE TITLE
Add Blood pressure sync

### ISSUE THREAD

**Issue by alvins711** [jaroslawhartman/withings-sync#106]
add Withings Blood Pressure info to Garmin Connect's new BP fields

**Comment by stynoo** [comment]
The page is supposed to be here (https://connect.garmin.com/modern/blood-pressure) but it's not active yet on my account. 

You can already help @alvins711 by figuring out if there is a way to upload (export/import) these new stats with a  .fit file as that is the method used to upload weight stats to Garmin atm.

**Comment by alvins711** [comment]
@stynoo You can enable the BP stats by changing your account's country to US from garmin.com (not connect.garmin.com). BP stats option will automatically show up in the connect.garmin.com and also the mobile app. I'll play around with export/import .fit file as suggested.

**Comment by alvins711** [comment]
@stynoo withings-sync retrieves the BP data from Withings but does not encode them into the .fit file. So data never gets imported to Garmin

**Comment by longstone** [comment]
I can confirm that blood pressure showed up, after switching location.
The script is modified (check PR) - I also did a (in my opinion) successful sync. 
For now, I don't see any data.

Feel free to try out the PR
