### ISSUE TITLE
3.6.0 not on pypi yet

### ISSUE THREAD

**Issue by thebruge** [jaroslawhartman/withings-sync#109]
Does it just take some time to appear for pip updates or there was a problem with the push to them? Latest for pip install still shows at 3.5.1, thanks.

**Comment by stv0g** [comment]
@longstone can I add you as a maintainer to the withings package on pypi.org?

**Comment by longstone** [comment]
Of course https://pypi.org/user/longstone/

**Comment by stv0g** [comment]
@longstone I added you as a maintainer to the project.

**Comment by longstone** [comment]
https://pypi.org/project/withings-sync/3.6.1/
