### ISSUE TITLE
 INFO - No Garmin username - skipping sync

### ISSUE THREAD

**Issue by plysdyret** [jaroslawhartman/withings-sync#120]
Hi

Installed with pip. No matter how I provide the Garmin credentials it says skipping sync. Python is version 3.9.17.

Suggestions? 

Mvh.

Torkil

**Comment by Cloud9Developer** [comment]
not affiliated with the project, but what's the exact command you are running (replacing your credentials with dummy values obviously)

**Comment by longstone** [comment]
Please try with the newest version and provide the debug log. Thank you

**Comment by XceptN** [comment]
Experiencing the same with pip and I have a debug log.. See below.
[withings-sync-debug-log-PI-obfuscated.log](https://github.com/jaroslawhartman/withings-sync/files/13636562/withings-sync-debug-log-PI-obfuscated.log)

**Comment by longstone** [comment]
Your are not on the latest version.
@jaroslawhartman please fix https://github.com/jaroslawhartman/withings-sync/issues/138 so users have the latest pip version available.

**Comment by jaroslawhartman** [comment]
Hi @longstone:  #138 fixed
