### ISSUE TITLE
Unable to connect to Garmin

### ISSUE THREAD

**Issue by Vinzf22** [jaroslawhartman/withings-sync#130]
Hi

I'm not enable to connect Garmin anymore.
I have the following message :

2023-09-28 18:49:27,970 - garmin - ERROR - 'NoneType' object is not subscriptable
2023-09-28 18:49:27,970 - garmin - ERROR - Unable to retrieve Garmin username! Most likely: incorrect Garmin login or password!
2023-09-28 18:49:28,276 - garmin - ERROR - Bad response during GC upload: 403

It was working well on sept 18th.
I didn't change my Garmin account or password (to be sure , I tried to connect with my current credentials to Garmin Connect website and it works well).

Could you help please ?

**Comment by stynoo** [comment]
Have you tried upgrading already?  This exact issue should be fixed in the latest version.

**Comment by RobertdWray** [comment]
> Hi
> 
> I'm not enable to connect Garmin anymore. I have the following message :
> 
> 2023-09-28 18:49:27,970 - garmin - ERROR - 'NoneType' object is not subscriptable 2023-09-28 18:49:27,970 - garmin - ERROR - Unable to retrieve Garmin username! Most likely: incorrect Garmin login or password! 2023-09-28 18:49:28,276 - garmin - ERROR - Bad response during GC upload: 403
> 
> It was working well on sept 18th. I didn't change my Garmin account or password (to be sure , I tried to connect with my current credentials to Garmin Connect website and it works well).
> 
> Could you help please ?

I upgraded and had the same error code. I can pull a verbose log later if you think that would be helpful.

**Comment by Vinzf22** [comment]
> Have you tried upgrading already? This exact issue should be fixed in the latest version.

Thanks, I upgraded dans it works well ! (I didn't know how to upgrade it before... but with a 'pip install withings-sync -U' it works well 😁)
Thank you again for your quick reply !

**Comment by Wiigian** [comment]
Thanks, v4.0.0 got it working again for me also!
