### ISSUE TITLE
Garth now natively supports upload as of [0.4.32](https://github.com/matin/garth/releases/tag/0.4.32).

### ISSUE THREAD

**Issue by longstone** [jaroslawhartman/withings-sync#139]
Garth now natively supports upload as of [0.4.32](https://github.com/matin/garth/releases/tag/0.4.32).

```python
with open("12129115726_ACTIVITY.fit", "rb") as f:
    uploaded = garth.client.upload(f)
```

Let me know if anyone runs into issues, and I can fix them.

_Originally posted by @matin in https://github.com/jaroslawhartman/withings-sync/issues/132#issuecomment-1740909987_

**Comment by jrast** [comment]
This is addressed in https://github.com/jaroslawhartman/withings-sync/pull/143
