### ISSUE TITLE
docker support for ARM?

### ISSUE THREAD

**Issue by DoctorEw** [jaroslawhartman/withings-sync#15]
I'm trying to get some automation set up on my raspberry pi 4 and when I try to run the docker container I get the following error:

`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:219: exec user process caused: exec format error`

Is there a way to get this program to play well with docker and kubernetes on the Pi? My current "automation" is running the docker task through windows powershell with the schedule manager which isn't exactly an elegant solution.

**Comment by stv0g** [comment]
Hi @DoctorEw,

Yes, I am planning to support this. We currently dont have a continuous integration pipeline for this project.

So will start with a script first to re-deploy the Docker images for multiple archs.

Cheers,

**Comment by kbeilix** [comment]
Hi @stv0g,

also just tried to run via Docker on a Pi3b. When executing the first run I get:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Is there some way around this or can I somehow assist in fixing it?

Cheers

**Comment by stv0g** [comment]
I havnt manage to build the image actually with that script. Somehow my Docker setup is broken.

Can somebody else test the `contrib/do_release.sh` script?

**Comment by kbeilix** [comment]
Tried to run it on the Raspberry 3b. Unfortunately without much success (which is likely due to my lack of docker knowledge...)

**Comment by kbeilix** [comment]
Tried again with the updated Dockerfile. Unfortunately again with an error. Commands used:

```
git clone https://github.com/jaroslawhartman/withings-sync.git
docker build - < Dockerfile
```

gives errormessage:

```
Step 4/6 : COPY . /src
 ---> a8761cd62c61
Step 5/6 : RUN cd /src &&     python3 ./setup.py install
 ---> Running in 8faa5f2d8f5c
python3: can't open file '/src/./setup.py': [Errno 2] No such file or directory
The command '/bin/sh -c cd /src &&     python3 ./setup.py install' returned a non-zero code: 2
```

I tried to add setup.py to /src using wget and also added python-setuptools to apt-get in Dockerfile but recieved erros that other files are missing. I am obviously missing how to properly add the file in /src.. Any hints?

**Comment by stv0g** [comment]
Please use the contrib/do_release.sh script

**Comment by kbeilix** [comment]
this unfortunately fails as  well. When running

```
chmod 777  ./contrib/do_release.sh
./contrib/dpo_release.sh
```

I get:

```
fatal: Tag 'v3.3.0' existiert bereits
Username for 'https://github.com': kbeilix
Password for 'https://kbeilix@github.com': 
remote: Permission to jaroslawhartman/withings-sync.git denied to kbeilix.
fatal: unable to access 'https://github.com/jaroslawhartman/withings-sync.git/': The requested URL returned error: 403
```

**Comment by stv0g** [comment]
The problem of this error lies within your development environment, not in the script.

**Comment by skatsavos** [comment]
I get the following error:

remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/jaroslawhartman/withings-sync.git/'
