### ISSUE TITLE
upload-service returns error 415 file type not supported

### ISSUE THREAD

**Issue by weberk** [jaroslawhartman/withings-sync#152]
Hi,

just tried to play arround with uploading a fit file compiled your way, but finally the upload failed with the follwing error:
Post to https://connect.garmin.com/upload-service/upload/.fit:
`{"detailedImportResult":{"uploadId":"","uploadUuid":null,"owner":33649038,"fileSize":0,"processingTime":1,"creationDate":"2023-11-07 08:03:47.138 GMT","ipAddress":null,"fileName":"bloodpressure_dummy.fit","report":null,"successes":[],"failures":[{"internalId":null,"externalId":null,"messages":[{"code":415,"content":"The file is of a type we do not support."}]}]}}%  
`
Is uploading generally still working with Garmin? Since I do not have a developer account I tried to upload the file via the Garmin Connect website from the browser as described here: https://support.garmin.com/en-US/?faq=Ht3ZP52Kju075uKvqTqu99

Regards - Klaus.

here the .FIT file "bloodpressure_dummy.fit" I used (base64 encoded string):
`DBBsAK0AAAAuRklUQAAAAAAGAwSMBASGAQKEAgKEBQKEAAEAAAAAAABApaw/////////CUEAADEAAgAChAEBAgH///9CAAAXAAz9BIYDBIwHBIYIBIYCAoQEAoQFAoQKAoQAAQIBAQIGAQILAQICQKWsPwAAAAD//////////////////////////04AADMACP0EhgAChAEChAIChAMChAQChAUChAYBAg5Apaw/eABQAF8AXQBeAFwAS6x3`

**Comment by longstone** [comment]
Can you please provide a run with debug log output?

**Comment by weberk** [comment]
Got it running now. I had a broken CRC at the end. https://www.fitfileviewer.com/ was very helpful. We can close this issue. Sorry for bothering you too much. 

Good news: after fixing CRC I could upload the file manually on Garmin Connect website>all activities>import
