### ISSUE TITLE
Sync fails with "INFO - No Garmin username - skipping sync"

### ISSUE THREAD

**Issue by XceptN** [jaroslawhartman/withings-sync#160]
Installed via pip:
- Python 3.10.12
- withings-sync script version 4.2.4 (was 4.1.0)

and token auth done.. Running sync fails with

    INFO - No Garmin username - skipping sync

with logs/debug attached at [withings-sync-debug-log-PI-obfuscated2.log](https://github.com/jaroslawhartman/withings-sync/files/13948759/withings-sync-debug-log-PI-obfuscated2.log)

This has been working months before .. I am pretty (1) sure that I am not doing something wrong..

**Comment by longstone** [comment]
Ill check later, but this seems suspicios 

withings-sync script version 4.1.0

**Comment by longstone** [comment]
Try 

--garmin-username XXXX --garmin-password YYYY

Instead of

--garmin-username=XXXX --garmin-password=YYYY

**Comment by longstone** [comment]
You have no weight measurements right?
Blood pressure is feature flag enabled:

--features BLOOD_PRESSURE

**Comment by longstone** [comment]
Its this way since inception. However, the error message is not correct.

**Comment by XceptN** [comment]
Solved. Thanks
