### ISSUE TITLE
INFO - No blood pressure data to sync for FIT file

### ISSUE THREAD

**Issue by Krata4** [jaroslawhartman/withings-sync#162]
Hello,

my sync stoped wotking with this INFO message:
INFO - No blood pressure data to sync for FIT file

Can you help me, ho to fix it please?

Thanks
Jirka

**Comment by longstone** [comment]
Please run the script with verbose and paste an anonymized log output.

**Comment by Krata4** [comment]
Probably my fault. Data after upgrade of library are uploaded. Sorry for interrupting you

**Comment by Krata4** [comment]
No issue
