### ISSUE TITLE
Token requests when running as a Windows Task

### ISSUE THREAD

**Issue by dnbrv** [jaroslawhartman/withings-sync#167]
I wrote a Batch script to sync once a day with a variable date parameter. When the script is executed manually, everything works fine. But when I run it from Windows Task Scheduler whether on schedule or on demand, I receive the error `Can't read config file ./.withings_user.json` and the prompt to get the token from Withings. The error re-occurs on the next run after providing an updated token.

I thought the issue was that the task was being executed under a different user and doesn't have access to `%appdata%\Python\Python312\site-packages\withings_sync`, but task properties are set to run under my account. What could be the issue?

**Comment by longstone** [comment]
I assume the issue ist resolving the home dir: 

`HOME = os.environ.get("HOME", ".")`
https://github.com/jaroslawhartman/withings-sync/blob/master/withings_sync/withings2.py#L12

and

`USER_CONFIG = os.environ.get("WITHINGS_USER", HOME + "/.withings_user.json")`
https://github.com/jaroslawhartman/withings-sync/blob/master/withings_sync/withings2.py#L21

Can you try set HOME?

**Comment by dnbrv** [comment]
I'm sorry for the dumbest question. My coding skills are only as good as using precise instructions and asking ChatGPT to debug.

Where should I set HOME environmental variable? Will it be on Windows level? I tried [this documentation](https://www.geeksforgeeks.org/python-os-environ-object/) for `os.environ` and the output list didn't have a HOME variable.

**Comment by harupong** [comment]
@dnbrv 
You use GUI to set environmental variables in Windows. 
ref. https://www.computerhope.com/issues/ch000549.htm

Instead of modifying "Path", try creating new user variable "HOME", and set the value of it to the address of the directory that `.withings_user.json` is located.

**Comment by dnbrv** [comment]
@harupong That worked! Thank you!

**Comment by dnbrv** [comment]
@harupong Nope. It worked when I set it up. The next time it triggered automatically, the token prompt came up again.

**Comment by longstone** [comment]
> @harupong Nope. It worked when I set it up. The next time it triggered automatically, the token prompt came up again.

can you run `set` in this scope, to ensure HOME is still configured?

**Comment by dnbrv** [comment]
@longstone Strangely, it has resolved itself and everything has been working fine for 2 months now.
