### ISSUE TITLE
Docker container stops in two seconds

### ISSUE THREAD

**Issue by TheGreatHorla** [jaroslawhartman/withings-sync#173]
I'm sure this is a stupid question but I'm new to docker. I installed docker desktop for windows, pulled your container but if I start it, it runs for two seconds and then stops. That makes it impossible to input the withings token in the Exec tab?

edit: ok, I used "copy docker run", added --interactive and now I can type things in the Exec tab but everything I type it says "not found". How do I input the token? Neither just the string, "token: string" or  "token : string" works.

log:
![Screenshot 2024-07-11 09 34 05](https://github.com/jaroslawhartman/withings-sync/assets/80214193/8a1d668c-1e3b-40c7-93b2-6a31d37c15af)

Exec tab:
![Screenshot 2024-07-11 09 33 30](https://github.com/jaroslawhartman/withings-sync/assets/80214193/f99b6bc4-a28f-4ebd-ac6d-cd6ede30efde)

**Comment by longstone** [comment]
Can you try running it like:

`docker run --interactive --tty --name withings ghcr.io/jaroslawhartman/withings-sync:master --garmin-username=<username> --garmin-password=<password>`

It shows you the URL you must visit, so you can get a token.

**Comment by longstone** [comment]
closing issue due to no updates
