### ISSUE TITLE
Withings-sync in Docker and token 

### ISSUE THREAD

**Issue by darekdm1972** [jaroslawhartman/withings-sync#180]
When I run app in docker I need to obtaining Withings authorisation (generate a new token) every time when a container is down and up. Is there a way to save the token in an environment variable so that the container can start after shutdown without my intervention?

**Comment by stynoo** [comment]
Yes, but do it with mounting .withings_user.json (see https://docs.docker.com/engine/storage/)

**Comment by darekdm1972** [comment]
Thank You. It works!
