### ISSUE TITLE
Broken 4.2.6 package?

### ISSUE THREAD

**Issue by cyberjunky** [jaroslawhartman/withings-sync#184]
Could it be that 4.2.6 is broken?
I cannot install my software with it's dependency, maybe .VERSION file missing?
```
Unable to install package garminconnect>=0.2.22: error: Failed to prepare distributions Caused by: Failed to download and build `withings-sync==4.2.6` Caused by: Build backend failed to determine requirements with `build_wheel()` (exit status: 1) [stderr] Traceback (most recent call last): File "<string>", line 14, in <module> File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel return self._get_build_requires(config_settings, requirements=[]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires self.run_setup() File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 522, in run_setup super().run_setup(setup_script=setup_script) File "/tmp/.tmp7Z60mn/builds-v0/.tmpdRcDkn/lib/python3.12/site-packages/setuptools/build_meta.py", line 320, in run_setup exec(code, locals()) File "<string>", line 15, in <module> File "<string>", line 10, in read FileNotFoundError: [Errno 2] No such file or directory: '/tmp/.tmp7Z60mn/sdists-v5/pypi/withings-sync/4.2.6/e7xKPoL_FRThITmSJMpJ9/withings_sync-4.2.6.tar.gz/.VERSION'```

**Comment by cyberjunky** [comment]
4.2.5 works, fixed the issue by pinning it.

**Comment by thebruge** [comment]
I am getting issues install with pip:

`rgallagher@Rich-MacBook-Air ~ % pip3 install withings-sync --upgrade
Requirement already satisfied: withings-sync in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.2.5)
Collecting withings-sync
  Using cached withings_sync-4.2.6.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rh/l01x2s9s40j88b85zdy9xx400000gn/T/pip-install-luqqggi8/withings-sync_f3ba131208cf42329c6361cddc7504f6/setup.py", line 15, in <module>
          version=read(".VERSION"),
                  ^^^^^^^^^^^^^^^^
        File "/private/var/folders/rh/l01x2s9s40j88b85zdy9xx400000gn/T/pip-install-luqqggi8/withings-sync_f3ba131208cf42329c6361cddc7504f6/setup.py", line 10, in read
          return open(os.path.join(os.path.dirname(__file__), fname)).read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/rh/l01x2s9s40j88b85zdy9xx400000gn/T/pip-install-luqqggi8/withings-sync_f3ba131208cf42329c6361cddc7504f6/.VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.`

**Comment by longstone** [comment]
this sould be fixed with https://pypi.org/project/withings-sync/4.2.7/
