### ISSUE TITLE
Password special characters

### ISSUE THREAD

**Issue by IcarusR** [jaroslawhartman/withings-sync#19]
This app will not work if Garmin password contains special characters.

I changed my Garmin password from a word to a more secure one containing %/? (special characters) & withings-sync failed to login to garmin. Eventually I changed y garmin password to one containing only letters & numbers & all works OK again.

**Comment by volodiaja** [comment]
This is weird. My password contains a # and it works well.

**Comment by IcarusR** [comment]
OK I will experiment more tomorrow evening.

**Comment by krohn** [comment]
My password contains a # and is working fine.
Just a guess: For ? % * etc maybe it's help to to escape them to \? \% \*

**Comment by stv0g** [comment]
I also can not reproduce this issue. Its likely caused by some escaping issues in your env vars.

See also: #17
