### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by harupong** [jaroslawhartman/withings-sync#191]
I have a scheduled job on GitHub Actions to setup & run withings-sync twice a day, and it stopped working one week ago.

From the GitHub Actions log, I found out that setuptools was not installed by simply running `pip install withings-sync` during setup, thus the error “ModuleNotFoundError: No module named 'pkg_resources’” when running `withings-sync`. 

I added a step to install setuptools in my GitHub Actions yaml file as well during setup, and it worked fine.

Is this the expected behavior? My environment is as follows. 

Python: 3.12.7
withings-sync: 4.2.7
OS: Ubuntu 22.04.5

**Comment by stynoo** [comment]
Yes it is, your github actions probably upgraded from an older python version to 3.12.

Python 3.12 has removed pkg_resources from the standard library (moved to setuptools):
https://docs.python.org/3/whatsnew/3.12.html

> [gh-95299](https://github.com/python/cpython/issues/95299): Do not pre-install setuptools in virtual environments created with [venv](https://docs.python.org/3/library/venv.html#module-venv). This means that distutils, setuptools, pkg_resources, and easy_install will no longer available by default; to access these run pip install setuptools in the [activated](https://docs.python.org/3/library/venv.html#venv-explanation) virtual environment.

**Comment by harupong** [comment]
@stynoo 
Understood. Thanks for the clarification. My bad that I upgraded Python to 3.12 w/o taking a closer look first.

BTW, thank you so much for all the time and effort you and @longstone are putting into this project. I really appreciate it.
