### ISSUE TITLE
Problems with attaining Token.

### ISSUE THREAD

**Issue by brisnick** [jaroslawhartman/withings-sync#192]
When using the URL 

https://account.withings.com/oauth2_user/authorize2?response_type=code&client_id=183e03e1f363110b3551f96765c98c10e8f1aa647a37067a1cb64bbbaf491626&state=OK&scope=user.metrics&redirect_uri=https://wieloryb.uk.to/withings/withings.html& 

to request the token, I now get the error: {"errors":[{"message":"redirect_uri_mismatch: The redirect URI provided is missing or does not match partner callback url"}]}

Indeed the redirect URI gives 

Not Found

This worked on one of my computers, but now I am setting up again in Docker it no longer works.

**Comment by Mask1205** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
