### ISSUE TITLE
Check if Deprecated Endpoints will affect the script

### ISSUE THREAD

**Issue by jaroslawhartman** [jaroslawhartman/withings-sync#20]
[Deprecated endpoints](https://support.withings.com/hc/en-us/articles/360016745358-Deprecating-access-and-refresh-tokens-endpoints)

**Comment by stynoo** [comment]
What do you think about implementing https://github.com/vangorra/python_withings_api ?  It seems like the go-to Withings api implementation that does all the heavy lifting for you.  It also includes the possibility to read out measurements that are originally not supported by this project (ex. sleep data as requested in another issue)
