### ISSUE TITLE
Import

### ISSUE THREAD

**Issue by Includes21** [jaroslawhartman/withings-sync#22]
Hello, is it possible to not import twice or more same weigth info if script already did it to Garmin?

**Comment by stv0g** [comment]
Either Garmin Connect should be clever enough to not re-import the weight, or withings-sync must be able to correlate existing weight-ins.

I am assuming, that Garmin Connect can't handle the first case, which leaves us only with the latter option.
For this we need to be able to fetch the past weight-ins from Garmin Connect, which I am not sure if its possible.

But on an other note: Why dont you want to import multiple weight-ins?
Shouldnt they only improve the quality of your measurements?
I see no reason not to do so.

Cheers,
stv0g

**Comment by stv0g** [comment]
This is also a duplicate of #23. Lets continue the discussion there
