### ISSUE TITLE
Replace Garmin username/password by OAuth flow and tokens

### ISSUE THREAD

**Issue by stv0g** [jaroslawhartman/withings-sync#3]
Do we really need to provide the username and password?

I guess having a similar authentication flow as for the Withings API should be possible

**Comment by jgrecu** [comment]
I guess it would be possible: https://developer.garmin.com/gc-developer-program/health-api/ but getting into the Garmin developer program is not as easy as with Withings. and documentation is well hidden. (https://connect.garmin.com/proxy/oauth-service-1.0/)

**Comment by matin** [comment]
Garth migration solved this
