### ISSUE TITLE
new version: multiple users

### ISSUE THREAD

**Issue by Bobonos89** [jaroslawhartman/withings-sync#32]
Hey there,

with the "old" versions I could easily edit and run the sync.py file from any location using abspath - I did that to upload data for 3 different garmin accounts from one shared withings account.

Apparently the file itself is not suggested to be executed as a script anymore - since the direct main call is missing. I tried to bring it back, but without success. Also there is no option to use secret.json for passwords anymore.

Is there a way to use this app just by executing sync.py and without prior installation?

It would be a real bummer if this cool feature was lost in editing for state of the art security...

Thank you!

**Comment by stv0g** [comment]
I guess this is related to #13. Please dont open multiple issues on the same problem

**Comment by Bobonos89** [comment]
sorry, really didn't see it when I checked.
