### ISSUE TITLE
Duplicates Created - Sync only measures since previous sync?

### ISSUE THREAD

**Issue by darrencope** [jaroslawhartman/withings-sync#37]
Perhaps I'm missing something obvious, but I have the tool running on startup of my PC. If I omit the --fromdate and --todate flags, it appears to just sync the last day. Is there a way to have it a) sync everything since last time it was run? and b) make sure no duplicates are created? How are folks that run this every 2-3 hours dealing with this?

**Comment by stv0g** [comment]
Its currently an open issue. Please see #23

Closing this as it is a duplicate.
