### ISSUE TITLE
Raspberry Pi 4 issue

### ISSUE THREAD

**Issue by skatsavos** [jaroslawhartman/withings-sync#44]
I have install withings-sync using pip on Raspberry Pi 4 ang i get the following error:

pi@raspberrypi:~ $ withings-sync
Traceback (most recent call last):
  File "/home/pi/.local/bin/withings-sync", line 5, in <module>
    from withings_sync.sync import main
  File "/home/pi/.local/lib/python2.7/site-packages/withings_sync/sync.py", line 170
    logging.info(f'Current TrainerRoad weight: {tr.weight} kg ')

Hopefully for now the older withings-garmin-v2 seems to work fine.

**Comment by Aior** [comment]
```
pip uninstall withings-sync
pip3 install withings-sync
```
have fun

**Comment by mirenbz** [comment]
This happened to me in a remote VPS as well. Fixed. Thanks!

**Comment by longstone** [comment]
> ```
> pip uninstall withings-sync
> pip3 install withings-sync
> ```
> 
> have fun

Seems that this resolves the issue! I'm going to close it.
