### ISSUE TITLE
Garmin login no longer working

### ISSUE THREAD

**Issue by MartinEmrich** [jaroslawhartman/withings-sync#47]
I have withings-sync running for a few weeks now without problems (Cronjob running daily). But since December 22nd, it no longer works, I get this message:

````
2021-12-30 22:55:27,695 - garmin - ERROR - 'NoneType' object has no attribute 'group'
2021-12-30 22:55:27,696 - garmin - ERROR - Unable to retrieve Garmin username! Most likely: incorrect Garmin login or password!
````
My credentials have not changed.

Note that the data upload still works, it seems to be only this message.

**Comment by krohn** [comment]
Same here. The error is reported, but data is uploaded. No change in Garmin-Credentials.

**Comment by RobertdWray** [comment]
Also having same.

**Comment by stynoo** [comment]
It's not really a breaking issue:  
Garmin changed the string layout for the VIEWER_ variables on Garmin Connect and the regex can no longer convert them to readable json entries.  This json data is only used to extract and display the Garmin username.  
Try https://github.com/stynoo/withings-sync/commit/e5b9f191dabfbd3022bdb515206b396cefbc915c and see if this fixes it.  If this runs okay I'll create a PR.

**Comment by cristian5th** [comment]
Hello.

Sorry for bumping in with a different subject but, is this script still working for you?

For several months already, I'm getting an error when trying to connect to Garmin. This is what I can get from their answer:
```
<title>Garmin: Maintenance</title>
<h1 class="app__heading">We’re sorry.</h1>
<p class="app__subheading">Something went wrong, and our site is temporarily unavailable.<br />We’re already working to get things back on course.</h2>
<h1>Access denied</h1>
<p>This website is using a security service to protect itself from online attacks.</p>
<li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&amp;clientId=GarminConnect&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&amp;consumeServiceTicket=false </li>
<li>Error reference number: 1020</li>
<li>Server ID: FL_19F235</li>
```

I read from Tapiriik that Garmin is still allowing to read data but not to write anymore. How is it that the script seems to be still working for you? Did you do some special step?

Thanks a lot.

**Comment by stynoo** [comment]
Yeah, it is working, but the Garmin API is a pain since it's protected by CloudFlare.  
I'd say it's about 50/50 right now that you land on that maintenance page?

**Comment by cristian5th** [comment]
Ok. Thank you.

For my case it is 100% not working. I stopped the programmed call to the script months ago and any manual attempt that I make is giving me the maintenance page.

**Comment by stynoo** [comment]
I did some more tests yesterday to try go get a more stable connection to the Garmin Connect page.  
What didn't work: 
- use cloudscraper's builtin randomizer to send different user-agents: it seems like Cloudflare detects this and the results are even worst.  
- increase cloudscaper's builtin  'wait' period from 5" to something higher: went up to 10" but the results are the same. 

What looks promising is detecting status code 403, wait a few seconds and retry for a maximum of 3 times: 

> 2022-01-06 12:03:12,287 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sso.garmin.com:443
2022-01-06 12:03:12,913 - garmin - DEBUG - Status code 403 detected... retrying after 5 seconds...  
2022-01-06 12:03:17,955 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sso.garmin.com:443  
2022-01-06 12:03:18,617 - garmin - DEBUG - Status code 403 detected... retrying after 5 seconds...  
2022-01-06 12:03:23,640 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): sso.garmin.com:443  
2022-01-06 12:03:26,409 - garmin - DEBUG - Garmin connection established after 3 tries.  
2022-01-06 12:03:27,690 - root - INFO - Fit file uploaded to Garmin Connect

You have to be careful though as Garmin WILL rate limit and put a temporary ban on your IP if you hammer their service.

**Comment by krohn** [comment]
> It's not really a breaking issue: Garmin changed the string layout for the VIEWER_ variables on Garmin Connect and the regex can no longer convert them to readable json entries. This json data is only used to extract and display the Garmin username. Try [stynoo@e5b9f19](https://github.com/stynoo/withings-sync/commit/e5b9f191dabfbd3022bdb515206b396cefbc915c) and see if this fixes it. If this runs okay I'll create a PR.
 
Coming back to the initial reason of this ticket, [stynoo@e5b9f19](https://github.com/stynoo/withings-sync/commit/e5b9f191dabfbd3022bdb515206b396cefbc915c) seems to work for me. I'd support a pull-request. 
Thank you!!

And just asking, no offence: Do you mind creating an extra ticket for the rate-limiting-issue of @cristian5th, as this is not directly related to @MartinEmrich nontype-error-issue of this ticket? Or is it just fine to mix two subjects in one ticket?

**Comment by stynoo** [comment]
> And just asking, no offence: Do you mind creating an extra ticket for the rate-limiting-issue of @cristian5th, as this is not directly related to @MartinEmrich nontype-error-issue of this ticket? Or is it just fine to mix two subjects in one ticket?
No need, there are already a couple of tickets open for this and a PR just popped up with an alternative solution for this.

**Comment by cristian5th** [comment]
The 403 issue is definitely solved with pull request #49.

Sorry. I didn't want to mix two issues in one. I was just popping into the discussion because I understood that the script was working correctly for you, and that was not the case for me since last summer.

**Comment by cristian5th** [comment]
No, it does not!

But now that I'm able to connect to Garmin, I have the NoneType error. I tried the solution proposed by @stynoo but I'm getting some weird error:
`garmin - ERROR - get_json() takes 2 positional arguments but 3 were given`

I honestly don't understand because I'm calling the get_json function with only 2 arguments:
`userdata = self.get_json(dashboard.text, "VIEWER_USERPREFERENCES")`

**Comment by mcia1** [comment]
For me the changes from @stynoo only partially work. I need to get the data out of "VIEWER_SOCIAL_PROFILE" and not "VIEWER_USERPREFERENCES". I integrated all of this in my fork, and the username is printed again now. I will create another pull request shortly.

**Comment by ciancim** [comment]
The initial error of this issue is solved together with the 403 error in the same [Pull Request](https://github.com/jaroslawhartman/withings-sync/pull/49)

**Comment by longstone** [comment]
@MartinEmrich since the PR from @ciancim is merged (kudos!!) it should work again. can you please retest and close the issue if it's working?

**Comment by MartinEmrich** [comment]
@longstone thanks!
No error messages anymore.
