### ISSUE TITLE
please bump the pip version

### ISSUE THREAD

**Issue by rob-miller** [jaroslawhartman/withings-sync#65]
Both the pip install and the setup.py file indicate version 3.3.1, but in order to get the --to-json output option I had to install from the cloned github directory.

**Comment by krohn** [comment]
+1

**Comment by rob-miller** [comment]
prefer if can improve json format before bumping, my latest proposal #70

**Comment by LsVzqz** [comment]
This would be good, thank you.

**Comment by stv0g** [comment]
Done https://pypi.org/project/withings-sync/3.4.0/
