### ISSUE TITLE
Log to stdout instead of stderr

### ISSUE THREAD

**Issue by morgenbart** [jaroslawhartman/withings-sync#7]
Dear Jarek,

the logging output currently goes to STDERR and not to STDOUT

Could you change that, so that logging output goes to STDOUT by default or that it would be possible to change it to STDOUT by configuration / parameter?

Background is that I want to run this as a cron job.

The place to change that technically is in sync.py, line 73, call to logging.basicConfig (set parameter "stream" to "sys.stdout").

Best regards,
Michael

**Comment by jaroslawhartman** [comment]
Hi Michael,

I agree, perhaps the way how the output is written is not very consistent. But for cronjob, typical way of handling this problem is to redirect STDERR to STDOUT and then write to a log, e.g.
```
jhartman@wieloryb:~$ crontab -l


00 10 * * * ( . ~/.profile; cd /home/jhartman/scripts/withings-garmin-v2/; date; ./sync.py --garmin-username=jaroslaw.hartman --trainerroad-user=jhartman 2>&1 ) >> /var/log/withings.log
```

(note `2>&1` in the line)

Take a look if this will work for you.
Best regards,
Jarek

**Comment by morgenbart** [comment]
Dear Jarek,

Thank you, that would certainly work.

But I think with this cron job configuration you don't get automatically informed when something goes wrong (exception).

But on the other hand one will probably notice sooner or later whether synchronization has stopped working, so an automatic notification is not really required.

For the time being I've just modified my local installation to log to STDOUT. Maybe I'll have a look at a pull request / fork some time later.

So I'm closing this ticket, thanks again for your quick reply!

Best regards,
Michael
