### ISSUE TITLE
SyntaxError on fresh install

### ISSUE THREAD

**Issue by sockRa** [jaroslawhartman/withings-sync#71]
I ran the installation to completion and when I enter `withings-sync -h` I get the following syntax error:

`Traceback (most recent call last):
  File "/home/pi/.local/bin/withings-sync", line 5, in <module>
    from withings_sync.sync import main
File "/home/pi/.local/lib/python2.7/site-packages/withings_sync/sync.py", line 170
    logging.info(f'Current TrainerRoad weight: {tr.weight} kg ')`

It seemes to have something to do with the quote. Anyone else having this issue?
I'm running this of a raspberry pi zero W.

**Comment by stynoo** [comment]
Python 2 is no longer supported.

**Comment by sockRa** [comment]
Python 3 was the solution.
