### ISSUE TITLE
Running issues with 3.4.0

### ISSUE THREAD

**Issue by LsVzqz** [jaroslawhartman/withings-sync#72]
Tried to get the "-h" to run, but ran into numerous syntax issues.  I'm fairly new to python, but was able to resolve it so that at least I get -h to run.  I tried to run --to-json, and I had to change more stuff in the sync.py and wtihings2.py to get it work, and it's working.. i think!  The resulting JSON only has  "access_token", "authentification_code", "last_sync", "refresh_token", and "userid", so I'm not sure if my account doesn't have full measurements (it should) or something else is wrong with the code.

I probably should get this code up for review, but I've never set that up. 

Issues were:
* SyntaxError for syncDict[dt]: (I changed it to be: if dt not in syncDict)
* Indentation Error with a large logging statement. I think I deleted it
* Within WithingsMeasure, self is not defined, so i took out the self's for the withings_table (withings2.py)
* In generate_jsondata, I changed datum to dataentry.

I attached the modified versions, as a txt file, into here for others that are more savvy with github and python than I am.

[sync.py.txt](https://github.com/jaroslawhartman/withings-sync/files/8980052/sync.py.txt)
[withings2 .py.txt](https://github.com/jaroslawhartman/withings-sync/files/8980053/withings2.py.txt)

**Comment by kikijiki** [comment]
Can confirm this worked for me, thank you for the fix.

**Comment by stv0g** [comment]
Thanks @LsVzqz and @kikijiki,

I've fixed the syntax errors and released v3.4.1.

The corresponding PyPi package will be up soon.
