### ISSUE TITLE
SSO Garmin error:  <h1>Access denied</h1>

### ISSUE THREAD

**Issue by arturo-salinas** [jaroslawhartman/withings-sync#80]
Hi,

I am getting this error:

</a>

        <h1 class="app__heading">We’re sorry.</h1>
        <p class="app__subheading">Something went wrong, and our site is temporarily unavailable.<br />We’re already working to get things back on course.</h2>

        <div class="app__error__details">
          <div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>You cannot access sso.garmin.com. Refresh the page or contact the site owner to request access.</p>
  <ul class="cferror_details">
    <li>Ray ID: 750c0e9a6f3495e5</li>
    <li>Timestamp: 2022-09-26 12:38:30 UTC</li>
    <li>Your IP address: 81.234.134.48</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&amp;clientId=GarminConnect&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&amp;consumeServiceTicket=false </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_128F174</li>
    <li>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</li>
  </ul>
</div>

Is this temporary or am I doing something wrong?

Best regards,

Arturo

**Comment by embear** [comment]
I'm getting the same error since Friday:

```
We’re sorry.

Something went wrong, and our site is temporarily unavailable.
We’re already working to get things back on course.

Access denied

You cannot access sso.garmin.com. Refresh the page or contact the site owner to request access.

  • Ray ID: 750c2f33784dbb67
  • Timestamp: 2022-09-26 13:00:45 UTC
  • Your IP address: 91.23.40.22
  • Requested URL: sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&clientId=GarminConnect&gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&consumeServiceTicket=false
  • Error reference number: 1020
  • Server ID: FL_470F240
  • User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
```

**Comment by StephenLasseter** [comment]
I only run the job twice a day and am getting the same failure with my last successful run being on the 23rs (Friday).  Sounds like maybe something upstream changed.

**Comment by gvb1234** [comment]
I also have the same failure. I wrote [garmin_upload.txt](https://github.com/jaroslawhartman/withings-sync/files/9673084/garmin_upload.txt), a little python/selenium/chrome automation to upload a fit file automatically to garmin connect.

As it is, the script uploads the file withings-sync-log.fit that resides in the same directory as the script itself. You can modify line 16 to point to another file. Username and password are hardcoded in lines 18-19.

As with all selenium browser automations, the script might fail at any point because the page takes to long to load, or garmin has made a change somewhere.

If you set debug=True on line 183, the script will stop right before clicking on "import data", so nothing gets sent to garmin.

Have fun.

**Comment by skatsavos** [comment]
Hi, i am having the same as well as

**Comment by embear** [comment]
I switched to https://github.com/La0/garmin-uploader for uploading for now. Flexible and scriptable.
Sadly I don't know enough about python to have a closer look at that implementation and get an idea why this still works. Possibly someone else can jump in?

**Comment by skatsavos** [comment]
> I switched to https://github.com/La0/garmin-uploader for uploading for now. Flexible and scriptable. Sadly I don't know enough about python to have a closer look at that implementation and get an idea why this still works. Possibly someone else can jump in?

from a first glance, it seems to check more things. It is difficult to say for sure what makes difference.
I can see apart from user and pass also uses a csrf_token. I will try to do some tests the following days.

**Comment by stynoo** [comment]
I did some test and it looks like Cloudflare caught up on http2 connections.  
When reverting to the earlier CloudScraper solution in [this](https://github.com/jaroslawhartman/withings-sync/pull/24/commits/c9cc18c1c065374f0047eb1af772bd17e95635c5) commit things seems to work again for me. 
@longstone I can't remember why we had to switch to http2 instead of this so I am not sure if this is a valid fix.

**Comment by stynoo** [comment]
If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

**Comment by starcat13** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

just tried - this version works for me, thanks!

**Comment by longstone** [comment]
> I did some test and it looks like Cloudflare caught up on http2 connections.  
> When reverting to the earlier CloudScraper solution in [this](https://github.com/jaroslawhartman/withings-sync/pull/24/commits/c9cc18c1c065374f0047eb1af772bd17e95635c5) commit things seems to work again for me. 
> @longstone I can't remember why we had to switch to http2 instead of this so I am not sure if this is a valid fix. 

I have no clue..

**Comment by JoGu01** [comment]
> I did some test and it looks like Cloudflare caught up on http2 connections. When reverting to the earlier CloudScraper solution in [this](https://github.com/jaroslawhartman/withings-sync/pull/24/commits/c9cc18c1c065374f0047eb1af772bd17e95635c5) commit things seems to work again for me. @longstone I can't remember why we had to switch to http2 instead of this so I am not sure if this is a valid fix.

It was a solution by @ciancim to some Garmin-Connect problems in this PR: https://github.com/jaroslawhartman/withings-sync/pull/49

**Comment by skatsavos** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

For me it didn;t work

**Comment by stynoo** [comment]
> For me it didn;t work
Can you share your (redacted) debug logs?

**Comment by skatsavos** [comment]
> > For me it didn;t work
> > Can you share your (redacted) debug logs?
I have slightly modified the sync.py(+ using a bit older version) but i do not think that makes difference:

  File "/home/pi/withings-garmin-v2/garmin.py", line 183, in login
    session = GarminConnect.get_session(email=username, password=password)
  File "/home/pi/withings-garmin-v2/garmin.py", line 103, in get_session
    raise APIException(f"SSO error {ssoresp.status_code} {ssoresp.text}")
garmin.APIException: SSO error 401 <!DOCTYPE html>


I remember in the past that was not working for me as well as.

I trued to manually inspect the post of https://sso.garmin.com/sso/login but in my browser, it logging works. 
I tried to include all the parameters, but that didn;t make any difference.

**Comment by colonel302** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

Thanks for the solution. I need to install Cloudscraper (pip3 install cloudscraper). After the installation the import to garmin works.

**Comment by RobertdWray** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

Didn't work for me. 

`    <h1 class="app__heading">We’re sorry.</h1>
        <p class="app__subheading">Something went wrong, and our site is temporarily unavailable.<br />We’re already working to get things back on course.</h2>

        <div class="app__error__details">
          <div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>You cannot access sso.garmin.com. Refresh the page or contact the site owner to request access.</p>
  <ul class="cferror_details">
    <li>Ray ID: 754f5dbbfa6182b1</li>
    <li>Timestamp: 2022-10-04 16:41:37 UTC</li>
    <li>Your IP address: 68.33.42.5</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&amp;clientId=GarminConnect&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&amp;consumeServiceTicket=false </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_413F394</li>
    <li>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</li>
  </ul>`

**Comment by m1lhaus** [comment]
Solution from @stynoo worked for me only after I changed my IP. Initially I got rejected multiple times, then I tested solution from @stynoo and got rejected as well. It seems that Cloudflare or Garmin is very sensitive on number of tries to log-in from particular IP. So I powered on my NordVPN, connected to VPN in my country and it worked. So you might get lucky if you try it again after some time you have tried that the last time. Or you can try to use your mobile phone internet ;)

**Comment by skatsavos** [comment]
> Solution from @stynoo worked for me only after I changed my IP. Initially I got rejected multiple times, then I tested solution from @stynoo and got rejected as well. It seems that Cloudflare or Garmin is very sensitive on number of tries to log-in from particular IP. So I powered on my NordVPN, connected to VPN in my country and it worked. So you might get lucky if you try it again after some time you have tried that the last time. Or you can try to use your mobile phone internet ;)

Similar behavior with me. At the beginning it didn;t work, but i tried again and now it works . (but i did not tried any further tests)

**Comment by maxpfandl** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

Thanks! Works for me too!

**Comment by StephenLasseter** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

That is working for me.  I checked out your modded branch, built it with podman, pushed to my private registry, and re-pointed my kubernetes manifests to that image and tag.  I had to authenticate the withings API, but after that it is working as expected.

**Comment by kbeilix** [comment]
> If someone wants to test, [this](https://github.com/stynoo/withings-sync/blob/modded/withings_sync/garmin.py) version of garmin.py is working for me.

works for me. Thanks a lot

**Comment by MartinEmrich** [comment]
yes, replaced that file, and it works for me, too. Thanks!

**Comment by AlmightyCZ** [comment]
Is there an easy way to replace this file in docker image that was installed using docker pull command as shown on the main page?

**Comment by m1lhaus** [comment]
> Is there an easy way to replace this file in docker image that was installed using docker pull command as shown on the main page?

Well the only way I see is to run the container with mounted folder from host (-v <host_path>:<container_path>) and copy the modified python file from host to the container. The image then stays modified. However it will be mounting your folder every time so think carefully which path you mount.

**Comment by AlmightyCZ** [comment]
> 
> Well the only way I see is to run the container with mounted folder from host (-v <host_path>:<container_path>) and copy the modified python file from host to the container. The image then stays modified. However it will be mounting your folder every time so think carefully which path you mount.
Thanks for the idea, I replaced all the garmin.py files I could find, I also had to install cloudscraper (`pip install cloudscraper`) and it seems to be working again.
Also in my case (being docker beginner user running it on a Synology NAS) I had to rename .withing_user.json temporarily to keep my container running (waiting for the token), otherwise it terminated before I could "docker exec" sh on it and run the copy/pip commands.
