### ISSUE TITLE
Docker Image not available anymore

### ISSUE THREAD

**Issue by Schischu** [jaroslawhartman/withings-sync#85]
Hei

I just noticed that 
https://registry.hub.docker.com/r/stv0g/withings-sync/
is not available anymore.

Is this by accident or will be have to create a new one?

I found already a fork by @mjha
https://hub.docker.com/r/mjha/withings-sync

Thanks.

**Comment by stv0g** [comment]
I think the latest Docker images are now on GitHubs container registry:

https://github.com/jaroslawhartman/withings-sync/pkgs/container/withings-sync

**Comment by stv0g** [comment]
I just checked the README. But it does not contain any references to the old image name.
Where did you found it?

**Comment by longstone** [comment]
> I think the latest Docker images are now on GitHubs container registry:
> 
> https://github.com/jaroslawhartman/withings-sync/pkgs/container/withings-sync

it works:

```
docker pull ghcr.io/jaroslawhartman/withings-sync:v3.4.4 
v3.4.4: Pulling from jaroslawhartman/withings-sync
2408cc74d12b: Downloading  393.2kB/2.799MB
...
```

**Comment by Schischu** [comment]
You are right. Thank you. I didn't notice the new url and was surprised to see today in my logs that watchtower wasn't able to update my docker anymore.

I will switch to new url!
