### ISSUE TITLE
Different Versions on github an pypi

### ISSUE THREAD

**Issue by JoGu01** [jaroslawhartman/withings-sync#88]
Hi,
after fixing the Auth-error in 3.5.0 the released Version on github (https://github.com/jaroslawhartman/withings-sync/releases) is still at 3.4.4.
The latest release on pypi is still at 3.4.2.
Is Anyone able to "release" 3.5.0 and sync it with pypi so it can be installed by pip?
Regards,
Jörg

**Comment by timmhayes** [comment]
@jaroslawhartman and @stv0g: I'm receiving errors running the old 3.4.2 code installed from pip. According to https://pypi.org/, the latest build (3.5.1) hasn't been published yet. Can either if you push a release? Thanks!

**Comment by stv0g** [comment]
I published v3.5.1 to pypi.org: https://pypi.org/project/withings-sync/3.5.1/

**Comment by timmhayes** [comment]
@stv0g Thanks for publishing that! However now I'm seeing the script error documented in Issue #94
