### ISSUE TITLE
You cannot access sso.garmin.com. Refresh the page or contact the site owner to request access

### ISSUE THREAD

**Issue by henne49** [jaroslawhartman/withings-sync#92]
I'm currently unable to use the tool. 

        <p class="app__subheading">Something went wrong, and our site is temporarily unavailable.<br />We’re already working to get things back on course.</h2>

        <div class="app__error__details">
          <div class="cf-error-details cf-error-1020">
  <h1>Access denied</h1>
  <p>You cannot access sso.garmin.com. Refresh the page or contact the site owner to request access.</p>
  <ul class="cferror_details">
    <li>Ray ID: 773384ef0e0390ae</li>
    <li>Timestamp: 2022-12-02 10:53:31 UTC</li>
    <li>Your IP address: X.X.X.X</li>
    <li class="XXX_no_wrap_overflow_hidden">Requested URL: sso.garmin.com/sso/login?service=https%3A%2F%2Fconnect.garmin.com%2Fmodern&amp;clientId=GarminConnect&amp;gauthHost=https%3A%2F%2Fsso.garmin.com%2Fsso&amp;consumeServiceTicket=false </li>
    <li>Error reference number: 1020</li>
    <li>Server ID: FL_472F25</li>
    <li>User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</li>
  </ul>
</div>

**Comment by cosandr** [comment]
I solved this by installing the version from github, i.e. `pip3 install --user 'git+https://github.com/jaroslawhartman/withings-sync@master'`

**Comment by henne49** [comment]
Thank you, that fixed it also for me!
